# Quantum's Application Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: astralfield-config
  namespace: astralfield
  labels:
    app.kubernetes.io/name: astralfield
    app.kubernetes.io/component: config
data:
  NODE_ENV: "production"
  PORT_WEB: "3000"
  PORT_API: "8080"
  LOG_LEVEL: "info"
  REDIS_PORT: "6379"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "astralfield"
  POSTGRES_USER: "astralfield"
  # Monitoring
  PROMETHEUS_PORT: "9090"
  GRAFANA_PORT: "3000"
  # Application Settings
  APP_NAME: "Astral Field"
  APP_VERSION: "3.0.0"
  # Performance
  NODE_OPTIONS: "--max-old-space-size=2048"
  # Security
  TRUST_PROXY: "true"
  # Real-time features
  SOCKET_IO_ORIGINS: "*:*"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: astralfield
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: loadbalancer
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Logging
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
        access_log /var/log/nginx/access.log main;

        # Performance
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_types text/plain text/css text/xml text/javascript application/javascript application/xml+rss application/json;

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
        limit_req_zone $binary_remote_addr zone=login:10m rate=1r/s;

        # Upstream servers
        upstream web_backend {
            least_conn;
            server astralfield-web:3000 max_fails=3 fail_timeout=30s;
        }

        upstream api_backend {
            least_conn;
            server astralfield-api:8080 max_fails=3 fail_timeout=30s;
        }

        server {
            listen 80;
            server_name _;

            # Security headers
            add_header X-Frame-Options SAMEORIGIN;
            add_header X-Content-Type-Options nosniff;
            add_header X-XSS-Protection "1; mode=block";
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # API routes with rate limiting
            location /api/ {
                limit_req zone=api burst=20 nodelay;
                proxy_pass http://api_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 5s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }

            # WebSocket support for real-time features
            location /socket.io/ {
                proxy_pass http://api_backend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            # Static files and web application
            location / {
                proxy_pass http://web_backend;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 5s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
            }
        }
    }