@echo off
echo Setting up Vercel environment variables...

echo Adding NODE_ENV...
echo production | vercel env add NODE_ENV production

echo Adding DATABASE_URL...
echo postgresql://neondb_owner:npg_rkDs2yUYZEQ7@ep-proud-pond-adntwlpd-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require | vercel env add DATABASE_URL production

echo Adding AUTH0_SECRET...
echo eJ984INJetDPrysB7C5jPskPW8mw8vaRl-ya456K06Dj-zElQLz-q3hB1eyXohZZ | vercel env add AUTH0_SECRET production

echo Adding AUTH0_ISSUER_BASE_URL...
echo https://dev-ac3ajs327vs5vzhk.us.auth0.com | vercel env add AUTH0_ISSUER_BASE_URL production

echo Adding AUTH0_CLIENT_ID...
echo hqbzaW4XOvGR8nfqsFx6r80WLKq19xkb | vercel env add AUTH0_CLIENT_ID production

echo Adding AUTH0_CLIENT_SECRET...
echo eJ984INJetDPrysB7C5jPskPW8mw8vaRl-ya456K06Dj-zElQLz-q3hB1eyXohZZ | vercel env add AUTH0_CLIENT_SECRET production

echo Adding NEXTAUTH_SECRET...
echo KP9SglHlLADxibEBjponfYzSH0VR1W8bxnFb8dLPVBU= | vercel env add NEXTAUTH_SECRET production

echo Adding REDIS_URL...
echo https://complete-satyr-49686.upstash.io | vercel env add REDIS_URL production

echo Adding UPSTASH_REDIS_REST_TOKEN...
echo AcIWAAIncDExNGI3NWZhMmZlMWM0NDIzOGQxMTc1YTZiMzVhMDFiMXAxNDk2ODY | vercel env add UPSTASH_REDIS_REST_TOKEN production

echo Environment variables set! Now deploying...
vercel --prod --yes

echo Deployment complete!
pause